name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag webdriverio-mocha:latest

    - name: Run the Docker image
      run: docker run -p 4444:4444 webdriverio-mocha:latest